version: '3'

includes:
  prediction-engine:
    taskfile: ./packages/prediction/engine/Taskfile.yaml
    dir: ./packages/prediction/engine
  fetcher:
    taskfile: ./packages/market-data/ohlc-fetcher/Taskfile.yaml
    dir: ./packages/market-data/ohlc-fetcher
  mock-server:
    taskfile: ./packages/mocking/mock-server/Taskfile.yaml
    dir: ./packages/mock-server
  feature-engineering:
    taskfile: ./packages/market-data/feature-engineering/Taskfile.yaml
    dir: ./packages/market-data/feature-engineering

dotenv:
  - '.env'

tasks:
  run:nats-server:
    desc: "Run NATS Server"
    silent: true
    cmds:
      - nats-server --jetstream
  
  run:project:
    desc: "Run all microservices directly"
    silent: true
    env:
      KRAKEN_URL: http://localhost:8000
    deps:
      - fetcher:run
      - feature-engineering:run
      - prediction-engine:run

  run:local-dependencies:
    desc: "Run test dependencies"
    silent: true
    deps:
      - run:nats-server
      - mock-server:run
  
  run:bdd:
    desc: "Run behave BDD tests"
    silent: true
    cmds:
      - behave -x

  new:service:
    desc: "Create a new microservice inside packages/<app_group>/<microservice>"
    silent: true
    vars:
      APP_GROUP: "{{.CLI_ARGS | splitList \" \" | first}}"
      SERVICE: "{{.CLI_ARGS | splitList \" \" | last}}"
    cmds:
      - bash ./utils/new-service.sh {{.APP_GROUP}} {{.SERVICE}}

  build:all:
    desc: "Build docker images for all latest tags available"
    env:
      DOCKER_URL_BASE: ghcr.io/astramercatorius
    cmds:
      - bash ./utils/build-n-tag.sh

  build:service:
    cmds:
      - ./utils/build.sh {{.SERVICE_NAME}}

  build:
    desc: "Runs new build process"
    deps:
      - task: build:service
        vars:
          SERVICE_NAME: market-data/feature-engineering
      - task: build:service
        vars:
          SERVICE_NAME: market-data/ohlc-fetcher
      - task: build:service
        vars:
          SERVICE_NAME: prediction/engine

  tag:all:
    desc: "Generate tags for each microservice based on conventional commits"
    silent: false
    internal: false
    cmds:
      - bash ./utils/tag-microservices.sh
