FROM danazkari/python-talib:3.12.5

ARG PROJECT_PATH

WORKDIR /app

COPY ${PROJECT_PATH}/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ${PROJECT_PATH} /app

CMD ["python", "src/main.py"]
