FROM python:3.12.5

RUN apt update && apt install libstdc++6 -y && apt clean \
  && wget https://github.com/TA-Lib/ta-lib/releases/download/v0.6.3/ta-lib-0.6.3-src.tar.gz \
  && tar -xvf ta-lib-0.6.3-src.tar.gz && cd /ta-lib-0.6.3 \
  && ./configure --prefix=/usr --build=`/bin/arch`-unknown-linux-gnu \
  && make && make install \
  && pip install --no-cache-dir TA-Lib \
  && cd / && rm -Rf /ta-lib-0.6.3

ENTRYPOINT [ "bash" ]
