name: Create tags for packages
run-name: Triggered by a ${{ github.event_name }} to ${{ github.ref }} with commit ${{ github.commit }}
on:
  push:
    branches:
      - main
jobs:
  Tag-Creation:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Calculate tags
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@users.noreply.github.com"
          task tag:all
      - name: Push tags
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    needs: [Tag-Creation]
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Add Docker Buildx setup for cross-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver: docker-container
          platforms: linux/amd64
      
      # Enable QEMU for cross-platform emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64
      
      - name: Log in to Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check tags
        run: |
          git config user.name "Github Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag -l
      - name: Prepare C-lib dependencies
        run: |
          apt update && apt install build-essential libstdc++6 -y && apt clean
          cd /tmp
          wget https://github.com/TA-Lib/ta-lib/releases/download/v0.6.3/ta-lib-0.6.3-src.tar.gz
          tar -xvf ta-lib-0.6.3-src.tar.gz && cd ta-lib-0.6.3
          ./configure --prefix=/usr --build=`/bin/arch`-unknown-linux-gnu
          make
          sudo make install
          sudo ldconfig
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Run build
        env:
          DOCKER_URL_BASE: ghcr.io/astramercatorius
        run: |
          task build
